### ISSUE TITLE
Go live

### ISSUE THREAD

**Issue by stokito** [freifunk-bielefeld/firmware-wizard#19]
Can we add a link to your firmware selector on [OpenWrt downloads page](https://openwrt.org/downloads)?

Is it mature or due to some bugs we can give a user incorrect link?

**Comment by mwarning** [comment]
Sure. But I hope we can have something better in a few months: https://projects.freifunk.net/#/projects?project=openwrt_firmware_wizard&lang=en ;-)

**Comment by mwarning** [comment]
As for bugs - not really. But images that do not have a recognizable hardware revision in the filename are  referenced by an "all" download link (as for "all" models types). Reading the wiki it might turn out that there are other hardware revisions that are not supported. This is a case that cannot be handled without reading all wiki pages...

**Comment by stokito** [comment]
Ok then if you don’t mind I’ll put a link on downloads page. Also it would be nice to have so statistics how many user used the wizard.

But what if we can parse wiki page instead https://openwrt.org/toh/views/toh_fwdownload 
It already contains links to download for all devices and it would be great to show an instruction for the specific device.

**Comment by stokito** [comment]
The downloads table is autogenerated https://openwrt.org/supported_devices/adding_to_toh
That’s interesting, maybe we can reuse the mechanism

**Comment by mwarning** [comment]
I have added a counter to the selector site.

As for the table of hardware. Parsing it was a pain (see https://forum.openwrt.org/t/firmware-wizard/9039/41), and I didn't want to have a cron job running to parse the toh on a regular basis.
